import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className={styles.welcome}>Welcome to Demo E-Commerce App</h1>
        <div className={styles.card}>
          <img
            src="https://images.unsplash.com/photo-1565208565380-02138793c3b0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80"
            className={styles.first_image}
          />
          <div className={styles.card_body}>
            <button>
              <center>Pay Now</center>
            </button>
            <hr />
            <center>
              <h5 className={styles.card_title}>Black Pants</h5>
            </center>
          </div>
        </div>
      </div>
    </div>
  );
}
